### ISSUE TITLE
issue with importing

### ISSUE THREAD

**Issue by luisdiogo2071317** [ouadie-lahdioui/generator-botkit#1]
When i was importing it got an error. I have installed yeoman globally and tested another generator of it and works. It says "`Cannot find module '../../lib/BotkitGreeting`" when doing "`yo botkit`"

**Comment by ouadie-lahdioui** [comment]
Hi @luisdiogo2071317,

You can use [Botkit CLI](https://github.com/howdyai/botkit/blob/master/bin/cli.js) instead to scaffold out a new project.

**Comment by luisdiogo2071317** [comment]
im just testing some bot templates from yeoman and that's the only one that got an error
